// Survival Probability sidebar cards — circular progress rings showing P(no breach) at 30/60/90 days.
// Also contains the Work Order Sheet drawer with PDF export (tc.oracle.v1).

"use client";

import React, { useState, useCallback } from "react";
import { FileText, Download, X, ClipboardList, AlertTriangle } from "lucide-react";
import type { SurvivalProbability, WorkOrder } from "../../lib/types";
import { cn } from "../../lib/utils";

// ─── Circular Progress Ring ───────────────────────────────────────────────────

interface SurvivalRingProps {
  probability: number; // 0.0 – 1.0
  horizon: 30 | 60 | 90;
}

function SurvivalRing({ probability, horizon }: SurvivalRingProps) {
  const pct = Math.round(probability * 100);
  const radius = 28;
  const circumference = 2 * Math.PI * radius;
  const dash = (probability * circumference).toFixed(1);
  const gap = (circumference - Number(dash)).toFixed(1);

  const color =
    pct >= 80
      ? "#10B981" // green
      : pct >= 50
      ? "#F59E0B" // amber
      : "#EF4444"; // red

  const labelColor =
    pct >= 80 ? "text-emerald-400" : pct >= 50 ? "text-amber-400" : "text-red-400";

  return (
    <div className="flex flex-col items-center gap-2">
      <div className="relative flex items-center justify-center w-16 h-16">
        <svg width="64" height="64" viewBox="0 0 64 64" className="-rotate-90">
          {/* Track ring */}
          <circle
            cx="32"
            cy="32"
            r={radius}
            fill="none"
            stroke="rgba(148,163,184,0.08)"
            strokeWidth="4"
          />
          {/* Progress arc */}
          <circle
            cx="32"
            cy="32"
            r={radius}
            fill="none"
            stroke={color}
            strokeWidth="4"
            strokeLinecap="round"
            strokeDasharray={`${dash} ${gap}`}
            style={{ filter: `drop-shadow(0 0 4px ${color}80)` }}
          />
        </svg>
        <span className={cn("absolute text-sm font-mono font-bold tabular-nums", labelColor)}>
          {pct}%
        </span>
      </div>
      <div className="text-center">
        <div className="text-[10px] font-mono text-slate-500 uppercase tracking-wider">
          {horizon}-Day
        </div>
        <div className={cn("text-[10px] font-mono font-bold", labelColor)}>
          {pct >= 80 ? "SAFE" : pct >= 50 ? "CAUTION" : "CRITICAL"}
        </div>
      </div>
    </div>
  );
}

// ─── Work Order Generator ─────────────────────────────────────────────────────

function buildWorkOrder(
  segmentId: string,
  segmentLabel: string,
  breachDay: number | null
): WorkOrder {
  const breachDate = breachDay !== null
    ? new Date(Date.now() + breachDay * 86_400_000)
    : new Date(Date.now() + 90 * 86_400_000);

  // Recommend maintenance 7 days before predicted breach
  const recommendedDate = new Date(breachDate.getTime() - 7 * 86_400_000);

  return {
    id: `WO-${segmentId.toUpperCase().replace("SEG-", "")}-${Date.now().toString(36).toUpperCase()}`,
    segmentId,
    segmentLabel,
    recommendedAction: "Machine Tamping + Lining & Levelling",
    recommendedDate: recommendedDate.toISOString().split("T")[0],
    urgencyDays: breachDay !== null ? breachDay - 7 : 83,
    estimatedCrewSize: 8,
    estimatedDurationHours: 6,
    estimatedTqiRecovery: 25,
    generatedAt: new Date().toISOString(),
  };
}

// ─── PDF Export (client-side blob) ───────────────────────────────────────────

function exportWorkOrderPDF(wo: WorkOrder) {
  const content = [
    "RAILWAY BOARD — NORTHERN RAILWAY DIVISION",
    "TRACKCHAIN ORACLE — AUTO-GENERATED WORK ORDER",
    "=".repeat(55),
    "",
    `Work Order ID:     ${wo.id}`,
    `Generated At:      ${new Date(wo.generatedAt).toLocaleString("en-IN")}`,
    "",
    "TRACK SEGMENT:",
    `  Segment ID:      ${wo.segmentId}`,
    `  Segment Label:   ${wo.segmentLabel}`,
    "",
    "RECOMMENDED ACTION:",
    `  Action:          ${wo.recommendedAction}`,
    `  Recommended Date:${wo.recommendedDate}`,
    `  Urgency:         Within ${wo.urgencyDays} days (before predicted breach)`,
    "",
    "RESOURCE ESTIMATE:",
    `  Crew Size:       ${wo.estimatedCrewSize} personnel`,
    `  Duration:        ${wo.estimatedDurationHours} hours`,
    `  Expected TQI Recovery: +${wo.estimatedTqiRecovery} points`,
    "",
    "RDSO AUTHORITY: C-7012 / EN13848-1",
    "CLASSIFICATION: PREDICTIVE PREVENTIVE MAINTENANCE",
    "",
    "=".repeat(55),
    "This work order was generated by the TrackChain Oracle AI Engine.",
    "Authorize via Chief Track Inspector before dispatch.",
  ].join("\n");

  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${wo.id}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Work Order Sheet ─────────────────────────────────────────────────────────

interface WorkOrderSheetProps {
  workOrder: WorkOrder;
  onClose: () => void;
}

function WorkOrderSheet({ workOrder: wo, onClose }: WorkOrderSheetProps) {
  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-4">
      <div
        className="fixed inset-0 bg-black/70 backdrop-blur-sm"
        onClick={onClose}
        aria-hidden="true"
      />
      <div className="relative z-10 w-full max-w-lg glass-heavy rounded-card p-6 shadow-2xl border border-white/[0.08]">
        {/* Header */}
        <div className="flex items-start justify-between gap-3 mb-5">
          <div>
            <div className="flex items-center gap-2">
              <ClipboardList size={16} strokeWidth={1.5} className="text-cyan-400" />
              <h2 className="text-sm font-mono font-bold text-slate-200 uppercase tracking-wider">
                RDSO Work Order
              </h2>
            </div>
            <p className="text-[10px] font-mono text-slate-500 mt-0.5">{wo.id}</p>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded text-slate-500 hover:text-slate-200 hover:bg-white/5 transition-colors"
            aria-label="Close work order"
          >
            <X size={16} strokeWidth={1.5} />
          </button>
        </div>

        {/* Urgency Banner */}
        <div className="flex items-center gap-2 bg-red-500/[0.08] border border-red-500/25 rounded-control px-3 py-2.5 mb-5">
          <AlertTriangle size={13} strokeWidth={1.5} className="text-red-400 shrink-0" />
          <span className="text-xs font-mono text-red-300">
            Action required within <strong>{wo.urgencyDays} days</strong> to prevent RDSO threshold breach
          </span>
        </div>

        {/* Fields */}
        <div className="space-y-3 text-xs font-mono">
          {[
            ["Segment", wo.segmentLabel],
            ["Recommended Action", wo.recommendedAction],
            ["Scheduled Date", wo.recommendedDate],
            ["Crew Size", `${wo.estimatedCrewSize} personnel`],
            ["Duration Estimate", `${wo.estimatedDurationHours} hours`],
            ["Expected TQI Recovery", `+${wo.estimatedTqiRecovery} points`],
            ["Authority", "RDSO C-7012 / EN13848-1"],
            ["Classification", "PREDICTIVE PREVENTIVE MAINTENANCE"],
          ].map(([label, value]) => (
            <div key={label} className="flex justify-between gap-4 border-b border-white/[0.04] pb-2">
              <span className="text-slate-500 shrink-0">{label}</span>
              <span className="text-slate-200 text-right">{value}</span>
            </div>
          ))}
        </div>

        {/* Actions */}
        <div className="flex gap-3 mt-5">
          <button
            onClick={() => exportWorkOrderPDF(wo)}
            className="flex-1 flex items-center justify-center gap-2 bg-gradient-to-r from-cyan-500 to-blue-600 text-white rounded-control py-2 text-xs font-mono font-bold hover:brightness-110 transition-all shadow-[0_0_12px_rgba(6,182,212,0.25)]"
          >
            <Download size={13} strokeWidth={1.5} />
            Export Work Order (.txt)
          </button>
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-control text-xs font-mono text-slate-400 bg-white/5 border border-white/10 hover:bg-white/10 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Main Survival Sidebar ────────────────────────────────────────────────────

interface SurvivalSidebarProps {
  survivalProbs: SurvivalProbability[];
  segmentId: string;
  segmentLabel: string;
  breachDayEstimate: number | null;
  className?: string;
}

export function SurvivalSidebar({
  survivalProbs,
  segmentId,
  segmentLabel,
  breachDayEstimate,
  className,
}: SurvivalSidebarProps) {
  const [showSheet, setShowSheet] = useState(false);
  const workOrder = useCallback(
    () => buildWorkOrder(segmentId, segmentLabel, breachDayEstimate),
    [segmentId, segmentLabel, breachDayEstimate]
  );
  const [wo] = useState<WorkOrder>(() => workOrder());

  return (
    <>
      <div className={cn("flex flex-col gap-5", className)}>
        {/* Survival heading */}
        <div>
          <h3 className="text-[10px] font-mono font-bold uppercase tracking-widest text-slate-400 mb-3">
            Asset Survival Probability
          </h3>
          <div className="flex items-start justify-around">
            {([30, 60, 90] as const).map((h) => {
              const sp = survivalProbs.find((s) => s.horizon_days === h);
              return (
                <SurvivalRing
                  key={h}
                  probability={sp?.probability ?? 1}
                  horizon={h}
                />
              );
            })}
          </div>
        </div>

        <div className="h-px bg-white/[0.05]" />

        {/* Work order generator */}
        <div className="flex flex-col gap-3">
          <h3 className="text-[10px] font-mono font-bold uppercase tracking-widest text-slate-400">
            Preventive Maintenance
          </h3>
          {breachDayEstimate !== null ? (
            <div className="text-[11px] font-mono text-slate-400 bg-amber-500/[0.06] border border-amber-500/20 rounded-control px-3 py-2.5">
              Oracle recommends scheduling maintenance{" "}
              <span className="text-amber-300 font-bold">
                {breachDayEstimate - 7} days from now
              </span>{" "}
              (7 days before predicted breach at Day +{breachDayEstimate}).
            </div>
          ) : (
            <div className="text-[11px] font-mono text-emerald-400/80 bg-emerald-500/[0.05] border border-emerald-500/20 rounded-control px-3 py-2.5">
              No breach predicted in 90-day window. Routine maintenance schedule is adequate.
            </div>
          )}
          <button
            onClick={() => setShowSheet(true)}
            className="flex items-center justify-center gap-2 bg-gradient-to-r from-cyan-500 to-blue-600 text-white rounded-control py-2 text-[11px] font-mono font-bold hover:brightness-110 transition-all shadow-[0_0_12px_rgba(6,182,212,0.20)] w-full"
          >
            <FileText size={13} strokeWidth={1.5} />
            Schedule Preventive Maintenance
          </button>
        </div>
      </div>

      {showSheet && (
        <WorkOrderSheet workOrder={wo} onClose={() => setShowSheet(false)} />
      )}
    </>
  );
}
